---
# tasks file for install_ftp

- name: Install FTP
  yum: name=vsftpd state=latest

- name: Start FTP
  service: name=vsftpd state=started enabled=yes

- name: Allow FTP port in Firewall
  firewalld: port=21/tcp permanent=true state=enabled
  notify: Restart Firewalld

- name: Allow FTP service in Firewall
  firewalld: service=ftp permanent=true state=enabled
  notify: Restart Firewalld
  
- name: Create home dir
  file:
    path: /var/ftp/pub
    state: directory
    mode: 0755

- name: Create upload dir
  file:
    path: /var/ftp/pub/upload
    state: directory
    mode: 0757

- name: Modify FTP configuation
  lineinfile:
    dest: /etc/vsftpd/vsftpd.conf
    backup: yes
    backrefs: yes
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: anonymous_enable=NO, line: anonymous_enable=YES }
    - { regexp: anon_upload_enable, line: anon_upload_enable=YES }
    - { regexp: anon_mkdir_write_enable, line: anon_mkdir_write_enable=YES }
  notify: Restart FTP

- name: Modify SElinux
  shell: setsebool -P allow_ftpd_anon_write on

- name: Modify SElinux
  shell: chcon -t public_content_rw_t /var/ftp/pub/upload/
