---
- name: Install Apache
  hosts: all
  become: yes
 
  vars:
    source_file: ./index.html
    dest_file: /var/www/html
 
  tasks:
  - name: Check Linux Version
    debug: var=ansible_os_family

  - block:

      - name: Install Apache for Debian
        apt: name=apache2 state=present

      - name: Copy web page
        copy: src={{ source_file }} dest={{ dest_file }}
        notify: Restart Apache Debian

      - name: Start Apache
        service: name=apache2 state=started enabled=yes

    when: ansible_os_family == "Debian"

 
  - block:

       - name: Install Apache for RedHat
         yum: name=httpd state=present
 
       - name: Copy web page
         copy: src={{ source_file }} dest={{ dest_file }} 
         notify: Restart Apache RedHat
 
       - name: Start Apache
         service: name=httpd state=started enabled=yes
 
    when: ansible_os_family == "RedHat"
 
  - name: Open HTTP
    firewalld:
      service: http
      permanent: true
      state: enabled
    notify:  Restart Firewalld

  - name: Open HTTPS
    firewalld:
      service: https
      permanent: true
      state: enabled
    notify: Restart Firewalld
  
  handlers:
  - name: Restart Apache RedHat
    service: name=httpd state=restarted
    when: ansible_os_family == "RedHat"
 
  - name: Restart Apache Debian
    service: name=apache2 state=restarted
    when: ansible_os_family == "Debian"
 
  - name: Restart Firewalld
    service: name=firewalld state=restarted
