---
- name: Install Apache Web Server
  hosts: all
  become: yes

  tasks:
  - name: add a single line, in this case the same as the comment but uncommented
    lineinfile: dest=/etc/default/grub
                regexp='^GRUB_CMDLINE_LINUX="'
                line='GRUB_CMDLINE_LINUX="crashkernel=auto rd.lvm.lv=centos/root rd.lvm.lv=centos/swap rhgb quiet net.ifnames=0 biosdevname=0"'
                state=present

  - name: Write grub configuration file
    command: grub2-mkconfig -o /boot/grub2/grub.cfg
