---
- name: Grub config
  hosts: all
  become: yes

  tasks:
  - name: Edit grub config
    lineinfile: dest=/etc/default/grub
                regexp='^GRUB_CMDLINE_LINUX="'
                insertafter='GRUB_CMDLINE_LINUX="'
                line='GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"'
                state=present

  - name: Write grub configuration file
    command: grub-mkconfig -o /boot/grub/grub.cfg
