---
- name: Remove Apache Web Server
  hosts: all
  become: yes

  tasks:

  - name: Remove Apache
    apt: name=apache2 state=absent

  - name: Remove web page 
    file: path='/var/www/html/index.html' state=absent

  - name: Close HTTP  
    firewalld:
      service: http
      permanent: true
      state: disabled
    notify:  Restart Firewalld  

  - name: Close HTTPS  
    firewalld:
      service: https
      permanent: true
      state: disabled
    notify: Restart Firewalld

  handlers:
    - name: Restart Firewalld
      service: name=firewalld state=restarted 

